import * as d3 from "d3";

export const variables = {
  pct_with_loan: {
    breaks: [0, 0.33, 0.4, 0.46, 0.54, 0.64, 2.25],
    scale: "%",
    multiplier: 100,
    mapbox: ["get", "pct_with_loan"],
    display: "% restaurants with loan",
    js: (v) => v.pct_with_loan,
  },
  loan_per_company: {
    breaks: [0, 12000, 24000, 38000, 55000, 91000, 200000],
    scale: "$",
    multiplier: 1,
    mapbox: ["get", "loan_per_company"],
    display: "Loan amount per restaurant",
    js: (v) => v.loan_per_company,
  },
  hispanic_pct: {
    breaks: [0, 0.08, 0.15, 0.25, 0.4, 0.6, 1],
    scale: "%",
    multiplier: 100,
    mapbox: ["get", "hispanic_pct"],
    color: (v) => d3.interpolateCividis(0.9 - ((v - 0.3) * 1) / 0.8),
    display: "% Hispanic",
    js: (v) => v.hispanic_pct,
  },
  black_and_hispanic: {
    breaks: [0, 0.15, 0.3, 0.45, 0.6, 0.75, 1],
    scale: "%",
    multiplier: 100,
    mapbox: ["+", ["get", "hispanic_pct"], ["get", "black_pct"]],
    color: (v) => d3.interpolateCividis(0.9 - ((v - 0.3) * 1) / 0.8),
    display: "% Black and Hispanic",
    js: (v) => v.hispanic_pct + v.black_pct,
  },
  med_income: {
    breaks: [0, 50000, 60000, 70000, 80000, 110000, 250000],
    scale: "$",
    multiplier: 1,
    mapbox: ["get", "med_income"],
    color: (v) => d3.interpolateCividis(((v - 0.3) * 1) / 0.8),
    display: "Median income",
    js: (v) => v.med_income,
  },
  asian_pct: {
    breaks: [0, 0.01, 0.03, 0.06, 0.1, 0.2, 0.75],
    scale: "%",
    multiplier: 100,
    mapbox: ["get", "asian_pct"],
    color: (v) => d3.interpolateCividis(0.9 - ((v - 0.3) * 1) / 0.8),
    display: "% Asian",
    js: (v) => v.asian_pct,
  },
  black_pct: {
    breaks: [0, 0.01, 0.03, 0.05, 0.3, 0.6, 0.85],
    scale: "%",
    multiplier: 100,
    mapbox: ["get", "black_pct"],
    color: (v) => d3.interpolateCividis(0.9 - ((v - 0.3) * 1) / 0.8),
    display: "% Black",
    js: (v) => v.black_pct,
  },
  loan_total: {
    breaks: [0, 200000, 6e5, 1.4e6, 2.6e6, 5.6e6, 40.2e6],
    scale: "$",
    multiplier: 1,
    mapbox: ["get", "loan_total"],
    display: "Total amount loaned",
    js: (v) => v.loan_total,
  },
  loan_cnt: {
    breaks: [1, 3, 8, 15, 25, 40, 200],
    scale: "",
    multiplier: 1,
    mapbox: ["get", "loan_cnt"],
    display: "# of loans",
    js: (v) => v.loan_cnt,
  },
  ncompanies: {
    breaks: [0, 5, 20, 40, 60, 90, 400],
    scale: "",
    multiplier: 1,
    mapbox: ["get", "ncompanies"],
    display: "# of restaurants",
    js: (v) => v.ncompanies,
  },
  population: {
    breaks: [0, 4000, 15000, 26000, 35000, 47000, 106000],
    mapbox: ["/", ["get", "tot_pop"], ["get", "loan_cnt"]],
    scale: " people",
    multiplier: 1,
    display: "Population",
    color: (v) => d3.interpolateCividis(((v - 0.3) * 1) / 0.8),
    js: (v) => v.tot_pop / v.loan_cnt,
  },
  density: {
    breaks: [0, 30e-6, 400e-6, 1200e-6, 3000e-6, 6000e-6, 20000e-6],
    mapbox: ["/", ["get", "tot_pop"], ["get", "shape_area"]],
    scale: " people per square km",
    multiplier: 1e6,
    display: "Density",
    color: (v) => d3.interpolateCividis(((v - 0.3) * 1) / 0.8),
    js: (v) => v.tot_pop / v.shape_area,
  },
  pct_white: {
    breaks: [0, 0.2, 0.4, 0.5, 0.65, 0.8, 1],
    mapbox: ["get", "white_pct"],
    multiplier: 1e2,
    scale: "%",
    display: "% White",
    color: (v) => d3.interpolateCividis(0.9 - ((v - 0.3) * 1) / 0.8),
    js: (v) => v.white_pct,
  },
  pct_native: {
    display: "% Native American",
    scale: "%",
    breaks: [0, 0.5e-2, 1e-2, 2e-2, 5e-2, 10e-2, 32e-2],
    multiplier: 1e2,
    mapbox: ["get", "amind_pct"],
    color: (v) => d3.interpolateCividis(0.9 - ((v - 0.3) * 1) / 0.8),
    js: (v) => v.amind_pct,
  },
};

export const interactiveVariables = [
  ["pct_with_loan", "loan_cnt", "ncompanies", "loan_total", "loan_per_company"],
  [
    "population",
    "density",
    "pct_white",
    "hispanic_pct",
    "black_pct",
    "asian_pct",
    "pct_native",
    "med_income",
  ],
];
